# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2365768f1f7d9e2cee3216e59b726ceb969f4f82d9bff700a56b140dc31f4e9e9f5a9bee9cadf4720fda3301134cb7dc8f8909fe232ee0335af0285c48fd36

test:
  secret_key_base: 2d81d971ad55b1460c3db24d6945547d27d6c53fdc021b5307376ce083d3d8f33fe1c6dd1591fc44d21221fdef48612b4a064c6bab6b8716ac0eb3b189b0a95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
